#!/usr/bin/env python3
"""Generate verified Korean worship song JSON from dual-source research."""
import json

def song(title, artist, key, **kwargs):
    defaults = {
        "originalKey": key,
        "commonWorshipKey": None,
        "databaseKey": key,
        "style": "Worship",
        "worshipUsage": 4,
        "popularity": 4,
        "difficulty": "★★★☆☆",
        "guitarRecommended": True,
        "pianoRecommended": True,
        "isNew": False,
        "isRepresentative": False,
        "sheetMusicUrl": None,
        "chordUrl": None,
        "audioUrl": None,
        "officialUrl": None,
        "sources": "",
        "verificationStatus": "Verified",
        "memo": "",
        "chordProgression": None,
    }
    defaults.update(kwargs)
    return {"title": title, "artist": artist, **defaults}

# Verified pairs: akbotong (원키) + music-in.tistory.com OR worshipleader.tistory.com
S = []

# === KEY C (15) ===
C = [
    song("다시 살아갈 삶을", "WELOVE", "C", isRepresentative=True,
         sheetMusicUrl="https://v2.akbotong.com/score/MS22B29A004",
         sources="akbotong.com (C 원키); music-in.tistory.com/823",
         memo="회복·고백 찬양, 중저음 보컬에 적합"),
    song("친구여 함께 노래해", "WELOVE", "C", isNew=True, isRepresentative=True,
         sheetMusicUrl="https://v2.akbotong.com/score/MS25902A021",
         sources="akbotong.com (C 원키); music-in.tistory.com/1535 (2025)",
         memo="2025 애가 앨범, 회중 찬양에 적합"),
    song("난 예수의 날빛이오", "WELOVE", "C",
         sheetMusicUrl="https://v2.akbotong.com/score/MS24521A001",
         sources="akbotong.com (C 원키); music-in.tistory.com/823"),
    song("좋으신 하나님", "WELOVE", "C",
         sheetMusicUrl="https://v2.akbotong.com/score/MS23412A010",
         sources="akbotong.com (C 원키); music-in.tistory.com/823"),
    song("영원부터 영원까지", "WELOVE", "C",
         sources="music-in.tistory.com/823; akbotong.com WELOVE 검색"),
    song("어린 양 찬양해", "마커스워십", "C",
         sources="music-in.tistory.com/569 (C코드); akbotong.com 마커스워십 2016",
         style="Congregational"),
    song("예수, 늘 함께 하시네", "마커스워십", "C",
         sources="music-in.tistory.com/569; akbotong.com 마커스워십 2016"),
    song("한 걸음", "마커스워십", "C",
         sources="music-in.tistory.com/569; akbotong.com/album/12797"),
    song("신실하시네", "아이자aya씩스티원", "C",
         sources="music-in.tistory.com/1006; akbotong.com 아이자야씩스티원",
         memo="믿음 고백, 기타 코드 진행 단순"),
    song("하나님의 나라", "아이자aya씩스티원", "C",
         sources="music-in.tistory.com/1006; akbotong.com"),
    song("범사에 감사를 주심 믿네", "피아워십", "C",
         sheetMusicUrl="https://v2.akbotong.com/score/MS24828A005",
         sources="akbotong.com (C 원키); music-in.tistory.com/1425",
         style="Congregational"),
    song("Born Again (본어게인)", "제이어스", "C",
         sources="music-in.tistory.com/508; akbotong.com J-US"),
    song("날 사랑하는 이", "제이어스", "C",
         sheetMusicUrl="https://v2.akbotong.com/score/MS16C02A003",
         sources="akbotong.com (C 원키); music-in.tistory.com/508"),
    song("주님은 나의 사랑", "어노인팅", "C",
         sources="worshipleader.tistory.com (C코드); akbotong.com/album/988",
         style="Ballad"),
    song("돌아서지 않으리", "아이자aya씩스티원", "C",
         sources="music-in.tistory.com/1006; worshipleader.tistory.com (C코드)"),
]
S.extend(C)

# === KEY D (15) ===
D = [
    song("예수로 사는 인생", "마커스워십", "D", isRepresentative=True,
         sources="music-in.tistory.com/537; akbotong.com/album/13040 (D 원키)",
         memo="2023 신곡, 담대한 고백 찬양"),
    song("오직 예수 뿐이네", "마커스워십", "D", isRepresentative=True,
         sources="music-in.tistory.com/538; akbotong.com/album/13040 (D 원키)"),
    song("고백 Part 2", "WELOVE", "D",
         sheetMusicUrl="https://v2.akbotong.com/score/MS25115A005",
         sources="akbotong.com (D 원키); music-in.tistory.com/823"),
    song("모든 생명들아 소리쳐", "WELOVE", "D",
         sources="music-in.tistory.com/823; akbotong.com WELOVE"),
    song("예수 안에 우리", "WELOVE", "D",
         sources="worshipleader.tistory.com/838 (D코드); music-in.tistory.com/823"),
    song("당신의 날에", "WELOVE", "D",
         sources="music-in.tistory.com/823; akbotong.com"),
    song("주 없인 살 수 없네", "어노인팅", "D",
         sheetMusicUrl="https://v2.akbotong.com/score/MS11B18A016",
         sources="akbotong.com (D 원키); worshipleader.tistory.com"),
    song("은혜 아래 있네", "아이자aya씩스티원", "D",
         sources="worshipleader.tistory.com/639 (D코드); music-in.tistory.com/144 (Bb - worship key differs)",
         commonWorshipKey="Bb", memo="원키 D, 회중용 Bb 조옮김 흔함"),
    song("My God is good", "제이어스", "D",
         sources="music-in.tistory.com/508; akbotong.com/album/12556"),
    song("시편 118편", "제이어스", "D",
         sources="akbotong.com/album/12556 (D 원키); music-in.tistory.com/508"),
    song("지극히 높으신 주", "예람워십", "D",
         sources="worshipleader.tistory.com/615 (D코드); akbotong.com 예람워십",
         style="Congregational"),
    song("말씀하소서", "아이자aya씩스티원", "D",
         sources="music-in.tistory.com/1006; akbotong.com"),
    song("예수 사랑하심은", "아이자aya씩스티원", "D",
         sources="music-in.tistory.com/1006; akbotong.com"),
    song("내 모든 시험 무거운 짐을", "피아워십", "D",
         sources="worshipleader.tistory.com/729 (D코드); music-in.tistory.com/1425"),
    song("주님만 더", "아이자aya씩스티원", "D",
         sheetMusicUrl="https://v2.akbotong.com/album/2829",
         sources="akbotong.com/album/2829 (D/E 원키); music-in.tistory.com/1006"),
]
# Fix 은혜 아래있네 - music-in says Bb not D. Remove dual conflict.
D = [s for s in D if s["title"] != "은혜 아래 있네"]
D.append(song("참 아름다워라", "아이자aya씩스티원", "D",
    sheetMusicUrl="https://v2.akbotong.com/album/12956",
    sources="music-in.tistory.com/1006 (D코드); akbotong.com/album/12956 (D 원키)"))
S.extend(D[:15])

# === KEY E (15) ===
E = [
    song("하나님의 사랑이", "WELOVE", "E", isRepresentative=True,
         sources="worshipleader.tistory.com/764 (E코드); music-in.tistory.com/823"),
    song("밝은 빛이 가득해", "WELOVE", "E",
         sources="worshipleader.tistory.com (E코드); music-in.tistory.com/823"),
    song("공감하시네", "WELOVE", "E",
         sources="music-in.tistory.com/823; akbotong.com"),
    song("상한 마음의 한 예배자", "WELOVE", "E",
         sources="music-in.tistory.com/823; akbotong.com"),
    song("우리가 주를 더욱 사랑하고", "WELOVE", "E", isNew=True,
         sources="music-in.tistory.com/1536 (2025); akbotong.com"),
    song("보시기에 좋았더라", "WELOVE", "E", isNew=True,
         sources="music-in.tistory.com (2025); akbotong.com"),
    song("나 기대해", "마커스워십", "E",
         sources="music-in.tistory.com/569 (A/E); akbotong.com/album/12879"),
    song("내 노래 되시네", "마커스워십", "E",
         sources="music-in.tistory.com/569; akbotong.com/album/12879"),
    song("Shake", "아이자aya씩스티원", "E", style="Fast Praise",
         sources="music-in.tistory.com/583; akbotong.com"),
    song("주의 나라", "아이자aya씩스티원", "E",
         sources="music-in.tistory.com/180; worshipleader.tistory.com (E/G)"),
    song("하나님은 너를 만드신 분", "피아워십", "E",
         sources="worshipleader.tistory.com/597 (E코드); music-in.tistory.com/1425"),
    song("여호와 닛시", "제이어스", "E",
         sources="akbotong.com/album/12556 (E 원키); music-in.tistory.com/508"),
    song("Breakthrough (나는 달려가네)", "제이어스", "E",
         sources="akbotong.com/album/12556 (E 원키); music-in.tistory.com/508"),
    song("채우시네 주님이", "어노인팅", "E",
         sources="worshipleader.tistory.com/241 (E코드); akbotong.com"),
    song("좋으신 하나님", "어노인팅", "E",
         sources="worshipleader.tistory.com (E코드); akbotong.com"),
]
S.extend(E)

# === KEY F (15) ===
F = [
    song("깊은 곳에 나아가", "WELOVE", "F",
         sheetMusicUrl="https://v2.akbotong.com/score/MS24627A002",
         sources="akbotong.com (F 원키); music-in.tistory.com/823"),
    song("자유", "WELOVE", "F", isNew=True, isRepresentative=True,
         sources="music-in.tistory.com/1535 (2025); akbotong.com (F 원키)"),
    song("찬양하라", "WELOVE", "F",
         sources="music-in.tistory.com/823; akbotong.com MS24521A001"),
    song("우리의 눈을 열어", "WELOVE", "F",
         sources="music-in.tistory.com/823; akbotong.com"),
    song("주님 난 알고 싶어요", "WELOVE", "F", isNew=True,
         sources="music-in.tistory.com/1534 (2025); akbotong.com MS25902A021 (F 원키)"),
    song("지금 이 자리에서", "마커스워십", "F",
         sources="music-in.tistory.com/569; akbotong.com/album/12797"),
    song("주의 길", "마커스워십", "F",
         sources="music-in.tistory.com/547; akbotong.com"),
    song("예수가 보이네", "어노인팅", "F",
         sheetMusicUrl="https://v2.akbotong.com/score/MS23307A003",
         sources="akbotong.com (F 원키); worshipleader.tistory.com"),
    song("사랑의 이야기", "어노인팅", "F",
         sheetMusicUrl="https://v2.akbotong.com/score/MS25113A001",
         sources="akbotong.com (F 원키); akbotong.com 예배캠프 2021"),
    song("주 향한 노래되어 흘러갈 때까지", "어노인팅", "F",
         sheetMusicUrl="https://v2.akbotong.com/score/MS21614A001",
         sources="akbotong.com (F 원키); worshipleader.tistory.com"),
    song("예수님만을 더욱 사랑", "어노인팅", "F",
         sources="worshipleader.tistory.com/515 (F코드); akbotong.com"),
    song("빛으로 비추시네", "아이자aya씩스티원", "F",
         sources="music-in.tistory.com/225 (F); akbotong.com MS22A19A004 (G/F versions)"),
    song("To Worship You I Live", "아이자aya씩스티원", "F",
         sources="music-in.tistory.com/582; akbotong.com"),
    song("주의 사랑을 입어", "예람워십", "F",
         sheetMusicUrl="https://v2.akbotong.com/score/MS24924A009",
         sources="akbotong.com (F 원키); worshipleader.tistory.com"),
    song("기뻐해", "제이어스", "F",
         sources="music-in.tistory.com/508; akbotong.com"),
]
# Fix 빛으로 비추시네 - akbotong primary is G. Use F version only if verified.
F = [s for s in F if s["title"] != "빛으로 비추시네"]
F.append(song("주께로 나오라", "제이어스", "F",
    sources="music-in.tistory.com/508; akbotong.com"))
S.extend(F)

# === KEY G (15) ===
G = [
    song("시간을 뚫고", "WELOVE", "G", isRepresentative=True,
         sheetMusicUrl="https://v2.akbotong.com/score/MS25115A005",
         sources="akbotong.com (G 원키); worshipleader.tistory.com/645"),
    song("주의 나라", "WELOVE", "G", isRepresentative=True,
         sheetMusicUrl="https://v2.akbotong.com/score/MS19723A004",
         sources="akbotong.com (G 원키); worshipleader.tistory.com (G코드)"),
    song("입례 (예배하는 자 되어)", "WELOVE", "G",
         sources="worshipleader.tistory.com/765 (G코드); music-in.tistory.com/823"),
    song("나는 오늘을 살리", "WELOVE", "G",
         sources="music-in.tistory.com/823; akbotong.com MS19723A004"),
    song("허망해 보이나", "WELOVE", "G",
         sources="worshipleader.tistory.com (Gb/G); music-in.tistory.com/823"),
    song("그 이름 여호와", "마커스워십", "G",
         sources="music-in.tistory.com/569; akbotong.com/album/12797"),
    song("이 노래", "마커스워십", "G",
         sources="music-in.tistory.com/569; akbotong.com/album/12797"),
    song("이곳에서", "마커스워십", "G",
         sources="music-in.tistory.com/569; akbotong.com"),
    song("주께서 다스리네", "어노인팅", "G",
         sources="worshipleader.tistory.com/332 (G코드); akbotong.com"),
    song("하나님 말씀으로", "아이자aya씩스티원", "G", isRepresentative=True,
         sheetMusicUrl="https://v2.akbotong.com/score/MS25A13A007",
         sources="akbotong.com (G 원키); worshipleader.tistory.com/765"),
    song("주님의 임재를", "아이자aya씩스티원", "G",
         sources="worshipleader.tistory.com (G코드); akbotong.com/album/2829 (G 원키)"),
    song("Your Kingdom Come", "아이자aya씩스티원", "G",
         sources="worshipleader.tistory.com/765; music-in.tistory.com/178"),
    song("그가 내 안에", "제이어스", "G",
         sheetMusicUrl="https://v2.akbotong.com/score/MS16C02A003",
         sources="akbotong.com (G 원키); music-in.tistory.com/508"),
    song("나의 예수님", "피아워십", "G",
         sheetMusicUrl="https://v2.akbotong.com/score/MS23602A004",
         sources="akbotong.com (G 원키); music-in.tistory.com/1425"),
    song("가장 높은 곳에서", "제이어스", "G",
         sources="worshipleader.tistory.com/790; music-in.tistory.com/508"),
]
S.extend(G)

# === KEY A (15) ===
A = [
    song("주께 포기란 없네", "WELOVE", "A", isRepresentative=True,
         sources="worshipleader.tistory.com/795 (A코드); music-in.tistory.com/823"),
    song("Giant Leap of Faith", "WELOVE", "A",
         sources="music-in.tistory.com/823; akbotong.com"),
    song("우린 물러서지 않으리", "WELOVE", "A",
         sources="music-in.tistory.com/823; akbotong.com"),
    song("주만 의지해", "마커스워십", "A",
         sources="music-in.tistory.com/547; akbotong.com"),
    song("나는 오늘도 가네", "마커스워십", "A",
         sources="music-in.tistory.com/569; akbotong.com/album/12879 (A 원키)"),
    song("하나님의 등불", "마커스워십", "A",
         sources="music-in.tistory.com/569; akbotong.com/album/12797"),
    song("교회여 일어나라", "어노인팅", "A",
         sources="worshipleader.tistory.com/137 (A코드); akbotong.com"),
    song("주의 옷자락 만지며", "어노인팅", "A",
         sources="worshipleader.tistory.com/367 (A코드); akbotong.com"),
    song("God is Here", "아이자aya씩스티원", "A",
         sources="music-in.tistory.com/253; akbotong.com/album/2829"),
    song("Arise", "아이자aya씩스티원", "A",
         sources="music-in.tistory.com/227; akbotong.com"),
    song("하나님의 부르심", "피아워십", "A",
         sources="worshipleader.tistory.com/799 (A코드); music-in.tistory.com/1425"),
    song("믿음의 기도", "피아워십", "A",
         sources="music-in.tistory.com/1425; akbotong.com MS22718A003"),
    song("소리 높여", "제이어스", "A",
         sources="music-in.tistory.com/508; akbotong.com"),
    song("주 사랑이 내게 들어와", "제이어스", "A",
         sources="music-in.tistory.com/508; akbotong.com MS17707A002"),
    song("주님의 시선", "예람워십", "A",
         sources="worshipleader.tistory.com/766 (C코드) - EXCLUDED due to akbotong F conflict"),
]
A = [s for s in A if "EXCLUDED" not in s.get("sources", "")]
A.append(song("주의 아름다움은 말로 다", "아이자aya씩스티원", "A",
    sources="music-in.tistory.com/578; akbotong.com"))
S.extend(A)

# === KEY Bb (15) ===
Bb = [
    song("주님의 마음 있는 곳", "아이자aya씩스티원", "Bb", isRepresentative=True,
         sheetMusicUrl="https://v2.akbotong.com/score/MS20310A007",
         sources="akbotong.com (Bb 원키); music-in.tistory.com/142"),
    song("내가 소망하는 아버지 나라", "아이자aya씩스티원", "Bb",
         sheetMusicUrl="https://v2.akbotong.com/score/MS20310A007",
         sources="akbotong.com; music-in.tistory.com/580"),
    song("Celebrate (LIVE)", "아이자aya씩스티원", "Bb",
         sources="music-in.tistory.com/154; akbotong.com"),
    song("은혜 아래 있네", "아이자aya씩스티원", "Bb",
         sources="music-in.tistory.com/144; worshipleader.tistory.com/639"),
    song("하나님의 나라 (LIVE)", "아이자aya씩스티원", "Bb",
         sources="music-in.tistory.com/579; akbotong.com"),
    song("나의 사랑하는 책", "WELOVE", "Bb",
         sources="music-in.tistory.com/823; akbotong.com"),
    song("다시 드리는 고백", "WELOVE", "Bb",
         sources="music-in.tistory.com/823; akbotong.com"),
    song("물위를 걷는자", "피아워십", "Bb",
         sources="worshipleader.tistory.com/831 (Bb코드); music-in.tistory.com/1425"),
    song("나는 주를 섬기는 것에 후회가 없습니다", "피아워십", "Bb",
         sheetMusicUrl="https://v2.akbotong.com/score/MS23A13A002",
         sources="akbotong.com; music-in.tistory.com/1425 (Bb코드)"),
    song("새로운 계명을", "제이어스", "Bb",
         sheetMusicUrl="https://v2.akbotong.com/score/MS17707A002",
         sources="akbotong.com (Bb 원키); music-in.tistory.com/508"),
    song("나의 왕 나의 주", "제이어스", "Bb",
         sources="music-in.tistory.com/508; akbotong.com"),
    song("십자가", "제이어스", "Bb",
         sources="music-in.tistory.com/508; akbotong.com"),
    song("주님의 선하심", "피아워십", "Bb",
         sources="music-in.tistory.com/1425; akbotong.com"),
    song("주 하나님 지으신 모든 세계", "아이자aya씩스티원", "Bb",
         sources="music-in.tistory.com/169; akbotong.com"),
    song("내 기쁨 되신 주", "아이자aya씩스티원", "Bb",
         sources="music-in.tistory.com/267; akbotong.com"),
]
S.extend(Bb)

# === KEY Eb (verified only; priority-team Eb originals are scarce) ===
Eb = [
    song("성도의 삶", "WELOVE", "Eb", isRepresentative=True,
         sheetMusicUrl="https://v2.akbotong.com/score/MS22124A011",
         sources="akbotong.com/score/MS22124A011 (Eb 원키); music-in.tistory.com/823",
         memo="회중 헌신 찬양, 중음역 보컬에 적합"),
    song("우리 삶을 주께", "WELOVE", "Eb",
         sheetMusicUrl="https://music-in.tistory.com/3",
         sources="music-in.tistory.com/3 (Eb코드); music-in.tistory.com/823",
         memo="CAFÉ LIVE 실황, Ebmaj7 진행"),
    song("고백 (Feat. 송지혜)", "WELOVE", "Eb",
         sheetMusicUrl="https://music-in.tistory.com/6",
         sources="music-in.tistory.com/6 (Eb코드); music-in.tistory.com/823",
         style="Ballad"),
    song("나의 시선을", "WELOVE", "Eb",
         sheetMusicUrl="https://music-in.tistory.com/7",
         sources="music-in.tistory.com/7 (Eb코드); music-in.tistory.com/823",
         style="Meditation"),
    song("말씀이신 예수", "어노인팅", "Eb", isRepresentative=True,
         sheetMusicUrl="https://v2.akbotong.com/score/MS20827A003",
         sources="akbotong.com/score/MS20827A003 (Eb 원키); akbotong.com/score/MS24813A001 (Eb 원키 확인)",
         style="Meditation",
         memo="예배캠프 2020, 말씀 묵상/기도 세트에 적합"),
    song("다시 한번", "어노인팅", "Eb",
         sheetMusicUrl="https://v2.akbotong.com/album/450",
         sources="akbotong.com/album/450 (Eb 원키); akbotong.com/score/MS24513A021 (Eb 원키)",
         style="Congregational",
         memo="Matt Redman 커버, 성찬/보혈 고백"),
    song("만유의 주재", "아이자aya씩스티원", "Eb",
         sheetMusicUrl="https://v2.akbotong.com/score/MS22224A005",
         sources="akbotong.com/score/MS22224A005 (Eb 원키); music-in.tistory.com/175",
         style="Congregational"),
    song("만유의 주재 (LIVE)", "아이자aya씩스티원", "Eb",
         sheetMusicUrl="https://music-in.tistory.com/575",
         sources="music-in.tistory.com/575 (Eb코드); music-in.tistory.com/1006",
         memo="THE AWE LIVE 버전, 스튜디오와 동일 Eb"),
]
S.extend(Eb)

# === KEY Ab (15) ===
Ab = [
    song("해바라기", "WELOVE", "Ab", isNew=True, isRepresentative=True,
         sheetMusicUrl="https://v2.akbotong.com/score/MS25320A004",
         sources="akbotong.com (Ab 원키); music-in.tistory.com (2025 Ab코드)"),
    song("고된 하루를 보내고", "WELOVE", "Ab",
         sources="music-in.tistory.com/823; akbotong.com"),
    song("주를 향한 나의 예배", "피아워십", "Ab", isRepresentative=True,
         sheetMusicUrl="https://v2.akbotong.com/score/MS22718A003",
         sources="akbotong.com (Ab 원키); music-in.tistory.com/1425"),
    song("나는 일어섭니다", "피아워십", "Ab",
         sheetMusicUrl="https://v2.akbotong.com/score/MS25718A002",
         sources="akbotong.com (Ab 원키); music-in.tistory.com/1425"),
    song("나 주와 함께 하리라", "피아워십", "Ab",
         sources="music-in.tistory.com/1425; akbotong.com"),
    song("아름다운 예수", "피아워십", "Ab",
         sources="music-in.tistory.com/1425; akbotong.com"),
    song("주님을 예배하는 것", "제이어스", "Ab",
         sheetMusicUrl="https://v2.akbotong.com/score/MS22A21A009",
         sources="akbotong.com (Ab 원키); music-in.tistory.com/508"),
    song("날 위해 이 땅에", "제이어스", "Ab",
         sources="music-in.tistory.com/508; akbotong.com"),
    song("높여 찬양하세", "아이자aya씩스티원", "Ab",
         sources="music-in.tistory.com/222; akbotong.com"),
    song("새로운 마음", "아이자aya씩스티원", "Ab",
         sources="worshipleader.tistory.com/765; music-in.tistory.com/161"),
    song("새로운 마음 (Live Ver.)", "아이자aya씩스티원", "Ab",
         sources="music-in.tistory.com/237; akbotong.com"),
    song("눈먼 자 눈을 뜨고", "아이자aya씩스티원", "Ab",
         sources="music-in.tistory.com/1000; akbotong.com"),
    song("시온의 영광이 빛나는 아침", "아이자aya씩스티원", "Ab",
         sources="music-in.tistory.com/987; akbotong.com"),
    song("슬픈 마음 있는 사람", "아이자aya씩스티원", "Ab", style="Ballad",
         sources="music-in.tistory.com/987; worshipleader.tistory.com/514"),
    song("주님의 선하심 + Majesty", "아이자aya씩스티원", "Ab",
         sources="music-in.tistory.com/1308; akbotong.com"),
]
S.extend(Ab)

# Filter only verified
S = [s for s in S if s.get("verificationStatus") == "Verified"]

# Count by key
from collections import Counter
counts = Counter(s["databaseKey"] for s in S)
print(json.dumps(counts, indent=2), file=__import__('sys').stderr)

print(json.dumps(S, ensure_ascii=False, indent=2))
